### ISSUE TITLE
TimePicker

### ISSUE THREAD

**Issue by fabriciomoreirao** [HorusSoftwareUY/MaterialDesignControlsPlugin#8] opened 2020-06-01 12:41 UTC
Android.Views.InflateException Message=Binary XML file line #20: Binary XML file line #20: Error inflating class android.widget.TimePicker

**Comment by AgustinBonilla** [comment] 2021-01-20 18:41
Hi @fabriciomoreirao 
I can't reproduce this issue in the repo example
What version of Xamarin.Forms are you using?
Are you using the repo example or your own project?

**Comment by AgustinBonilla** [comment] 2023-05-18 18:30
We have decided to temporarily close it as it may be out of date. However, if you experience this issue again in the future please feel free to reopen the incident so that we can investigate further!

**Closed by AgustinBonilla** 2023-05-18 18:30 UTC
Labels: question
